/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Student;
import Services.CourseService;
import Services.StudentService;
import databse.JsonDatabaseManager;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTable;


public class StudentDashboard extends javax.swing.JFrame {

    

    private JPanel contentPanel;
    private CardLayout cardLayout;

    private String studentId;
    private JsonDatabaseManager dbManager;
    private StudentService studentService;
    private Student currentStudent;
    
    private Lessons accessLessonPanel;
    private LessonContent lessonContentPanel;
    private CourseService courseService;
    
    public StudentDashboard(JsonDatabaseManager dbManager, String studentId) {
        initComponents();
        
   this.studentId = studentId;
        this.dbManager = dbManager;
        this.currentStudent = (Student) dbManager.getUserById(studentId);
        this.studentService = new StudentService(dbManager, currentStudent);

        initComponents();
        initCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Enroll = new javax.swing.JButton();
        ViewCourses1 = new javax.swing.JButton();
        AccessLesson = new javax.swing.JButton();
        CompleteLesson = new javax.swing.JButton();
        Enroll1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Enroll.setBackground(new java.awt.Color(153, 153, 255));
        Enroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Enroll.setForeground(new java.awt.Color(255, 255, 255));
        Enroll.setText("Enroll in a Course");
        Enroll.setBorderPainted(false);
        Enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollActionPerformed(evt);
            }
        });

        ViewCourses1.setBackground(new java.awt.Color(153, 153, 255));
        ViewCourses1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewCourses1.setForeground(new java.awt.Color(255, 255, 255));
        ViewCourses1.setText("View Availble Courses");
        ViewCourses1.setBorderPainted(false);
        ViewCourses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCourses1ActionPerformed(evt);
            }
        });

        AccessLesson.setBackground(new java.awt.Color(153, 153, 255));
        AccessLesson.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AccessLesson.setForeground(new java.awt.Color(255, 255, 255));
        AccessLesson.setText("Access Lessons");
        AccessLesson.setBorderPainted(false);
        AccessLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessLessonActionPerformed(evt);
            }
        });

        CompleteLesson.setBackground(new java.awt.Color(153, 153, 255));
        CompleteLesson.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CompleteLesson.setForeground(new java.awt.Color(255, 255, 255));
        CompleteLesson.setText("Mark Lesson Completed");
        CompleteLesson.setBorderPainted(false);
        CompleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteLessonActionPerformed(evt);
            }
        });

        Enroll1.setBackground(new java.awt.Color(153, 153, 255));
        Enroll1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Enroll1.setForeground(new java.awt.Color(255, 255, 255));
        Enroll1.setText("View Enrolled Courses");
        Enroll1.setBorderPainted(false);
        Enroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enroll1ActionPerformed(evt);
            }
        });

        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccessLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Enroll, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(CompleteLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewCourses1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(Enroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(ViewCourses1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Enroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(AccessLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CompleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollActionPerformed
        cardLayout.show(contentPanel, "enroll");
    }//GEN-LAST:event_EnrollActionPerformed

    private void ViewCourses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCourses1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "available");
    }//GEN-LAST:event_ViewCourses1ActionPerformed

    private void AccessLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessLessonActionPerformed
        // TODO add your handling code here:
         cardLayout.show(contentPanel, "lessons");
    }//GEN-LAST:event_AccessLessonActionPerformed

    private void CompleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteLessonActionPerformed
        // TODO add your handling code here:
         cardLayout.show(contentPanel, "complete");
    }//GEN-LAST:event_CompleteLessonActionPerformed

    private void Enroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enroll1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "enrolled");
    }//GEN-LAST:event_Enroll1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showPanel(String panelName) {
    cardLayout.show(contentPanel, panelName);
}
    private void initCards() {
        cardLayout = (CardLayout) contentPanel.getLayout();

        // Initialize panels
        accessLessonPanel = new Lessons(this, courseService);
        lessonContentPanel = new LessonContent(this, courseService,studentService);

        // Add to contentPanel
        contentPanel.add(accessLessonPanel, "lessons");
        contentPanel.add(lessonContentPanel, "lessonContent");

        cardLayout.show(contentPanel, "lessons");
    }
    
    public StudentService getStudentService() {
    return this.studentService;
}
    public JPanel getContentPanel() {
    return contentPanel;
}   
    public LessonContent getLessonContentPanel() {
        return lessonContentPanel;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true); 
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccessLesson;
    private javax.swing.JButton CompleteLesson;
    private javax.swing.JButton Enroll;
    private javax.swing.JButton Enroll1;
    private javax.swing.JButton ViewCourses1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
